Utils: Add dynamic fetching of guild emojis
SerenityOS/discord-bot pull request #13
Opened 2021-04-26 19:20 UTC by PossiblyAShrub

Based off of #11 
> In the future it might be beneficial to use the discordjs api somehow to not hardcode the emoji ID.

This pr creates a new function `getEmoji` which fetches the guild (server) in which a message was received for a custom emoji.
The feature is then used by the `issueCommand` and `prCommand` for the `:sadcaret:` emoji.

2021-04-26 19:22 UTC, bgianfo commented
This is great, thanks! Can you rebase on top of latest master, and also fix the ManCommand that I just added?

2021-04-26 19:32 UTC, bgianfo requested changes

2021-04-26 19:32 UTC, bgianfo commented on src/commands/prCommand.ts
> +        const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
Should we just have a `getSadCaret()` utility on top of your new `getEmoji(...)` utility?

2021-04-26 19:35 UTC, IdanHo reviewed
Nice work, just a couple suggestions

2021-04-26 19:35 UTC, IdanHo commented on src/commands/issueCommand.ts
> +                    const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
Might be worth while to cache this as a static member field, since the result shouldn't change during a single runtime.

2021-04-26 19:35 UTC, IdanHo commented on src/util/emoji.ts
> +    const emoji = message.guild.emojis.cache.find(emoji => emoji.name === name);
We shouldn't rely on the existing cache to have the emoji (since by default that would only be populated on the first message the bot parses that includes that emoji), and instead should ask discordjs to resolve it (either from the cache as you currently do or by requesting it from the discord API) via `guild.emojis.resolve(name)`

2021-04-26 19:38 UTC, PossiblyAShrub commented on src/commands/issueCommand.ts
> +                    const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
I'll look into that.

2021-04-26 19:38 UTC, PossiblyAShrub commented on src/util/emoji.ts
> +    const emoji = message.guild.emojis.cache.find(emoji => emoji.name === name);
Thanks, I can fix that.

2021-04-26 20:14 UTC, PossiblyAShrub commented on src/util/emoji.ts
> +    const emoji = message.guild.emojis.cache.find(emoji => emoji.name === name);
I haven't been able to find much on fetching emojis from discord dynamically. This resource: https://discordjs.guide/popular-topics/reactions.html#custom-emojis recommends reading them from the cache.
Also, I haven't been able to create a scenario where the bot doesn't have the emoji in it's cache. (brand new server, no messages, works fine)
So, it seems like this is already the best way to handle this?

2021-04-26 20:14 UTC, PossiblyAShrub commented on src/commands/issueCommand.ts
> +                    const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
Emoji caching & invalidation seems to be provided by the discordjs API. Then the only added overhead is then reading a cache every time we fetch an emoji.
Also, this might be a premature optimisation that would complicate the code further than need be. (we'd have to find some way to keep the cached emoji and invalidate it if necessary)

2021-04-26 20:17 UTC, PossiblyAShrub commented on src/commands/prCommand.ts
> +        const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
Just pushed those changes now.

2021-04-26 20:19 UTC, IdanHo commented on src/util/emoji.ts
> +    const emoji = message.guild.emojis.cache.find(emoji => emoji.name === name);
#resolve methods on discordjs cache managers ensure that if the object exists it will be returned, unlike the cache which does not. looking at the source code of discordjs in the case of emojis you are right that it always uses the cache, but looks like it uses a O(1) lookup instead of iterating over the whole cache, so using it is probably still a better idea :)

2021-04-26 20:20 UTC, IdanHo commented on src/commands/issueCommand.ts
> +                    const sadcaret = getEmoji(parsedUserCommand.originalMessage, "sadcaret");
yeah, i guess the discordjs cache is enough

2021-04-26 20:48 UTC, bgianfo approved these changes

2021-04-26 20:59 UTC, bgianfo commented
I'll merge once @IdanHo and you figure out what to do about the caching convo :+1:

2021-04-26 23:29 UTC, PossiblyAShrub commented on src/util/emoji.ts
> +    const emoji = message.guild.emojis.cache.find(emoji => emoji.name === name);
So, I've implemented something along those lines. Discordjs does not let me index into the cache with the emoji name (ie. `:sadcaret:`). My solution was to create my own cache that does. This means we get O(1) in the best/most common case.
Thanks again for the feedback :)

2021-04-27 04:17 UTC, IdanHo approved these changes
LGTM

2021-04-27 04:36 UTC, merged