ManCommand: Implement embed based format
SerenityOS/discord-bot pull request #20
Opened 2021-04-27 13:37 UTC by networkException

- Send an Embed instead of a markdown codeblock for a man page
- Add emojis to be able to toggle between a collapsed and an extended view

2021-04-27 13:55 UTC, IdanHo reviewed
Nice work :) i suggested a couple of improvements, and your last 2 commits should be squashed into the ones before as well

2021-04-27 13:55 UTC, IdanHo commented on src/commands/manCommand.ts
> +                const minimizeEmote: string | null = getMinimize(message);
Theres no point to specifying types for immediatly initialized constants
(This is repeated in a couple other places as well)

2021-04-27 13:55 UTC, IdanHo commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
instead of adding a callback that will be fired for *every* discord event you can add a specific event handler
`client.on("messageReactionAdd", (messageReaction, user) => {`

2021-04-27 13:57 UTC, networkException commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
*sigh* I wish it was that easy. Sadly discord.js doesn't trigger messageReactionAdd if the message got sent before the bot started.

2021-04-27 13:58 UTC, networkException commented on src/commands/manCommand.ts
> +                const minimizeEmote: string | null = getMinimize(message);
Sure I can remove that, its just a habbit to specify all types even if they are easily inferrable, probably from working with java :^)

2021-04-27 14:03 UTC, networkException commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
Also there doesn't seem to be a way to get the id of the user that reacted from MessageReaction (at least from looking at the typings)

2021-04-27 14:04 UTC, IdanHo commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
> Also there doesn't seem to be a way to get the id of the user that reacted from MessageReaction (at least from looking at the typings)

the `user` parameter provides that information

2021-04-27 14:14 UTC, networkException commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
I'm sadly unable to reproduce messageReactionAdd working https://youtu.be/3Ak16iOVutc

2021-04-27 14:18 UTC, networkException commented on src/index.ts
> +    if (event.t === "MESSAGE_REACTION_ADD") {
oh I missed the partials array you have to give to Client

2021-04-28 00:17 UTC, bgianfo requested changes

2021-04-28 05:56 UTC, networkException commented on src/apis/githubAPI.ts
> +            url: `https://github.com/${this.repository}/blob/master/${this.man_path}/man${section}/${page}.md`,
```ts
const path = `${this.man_path}/man${section}/${page}.md`;
```
Is the best I can do here

2021-04-28 06:11 UTC, bgianfo approved these changes

2021-04-28 06:13 UTC, bgianfo commented
Can you squash the cleanup commits please? Besides that @IdanHo waiting on your final approval to merge.

2021-04-28 06:41 UTC, IdanHo commented
LGTM, just waiting for the cleanup commits squash as well

2021-04-28 07:03 UTC, IdanHo approved these changes

2021-04-28 07:28 UTC, merged