User: Add User command
SerenityOS/discord-bot pull request #381
Opened 2022-02-16 03:11 UTC by u9g

2022-02-16 03:51 UTC, u9g commented
I have absolutely no idea how to squash the merge commit

2022-02-17 12:57 UTC, networkException requested changes

2022-02-17 12:57 UTC, networkException commented on src/commands/githubCommand.ts
> -    }
The embed refactor should probably go in a seperate commit

2022-02-17 12:57 UTC, networkException commented on src/commandHandler.ts
> +                    name.toLowerCase() === interaction?.message?.interaction?.commandName
The first two `.?` can be replaced with just `.`, `interaction` is `SelectMenuInteraction` in this context and as such non nullish and `message` is `GuildCacheMessage`, as such also non nullish.

2022-02-17 12:57 UTC, networkException commented on src/commandHandler.ts
> +            console.trace("matchedCommand.handle(Select|Context)Menu failed", error);
(this is very bikeshed-y)

more common would be shell syntax to express this I think: `matchedCommand.handle{Select,Context}Menu failed`

2022-02-17 12:57 UTC, networkException commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
Instead of listing all issues and pull requests (I'm guessing it will return 100 in any case because of the page size), its better to use the search api: [https://api.github.com/search/issues?q=repo:SerenityOS/serenity+author:awesomekling](https://api.github.com/search/issues?q=repo:SerenityOS/serenity+author:awesomekling)

```ts
this.octokit.search.issuesAndPullRequests({
    q: "repo:SerenityOS/serenity+author:awesomekling",
});
```

2022-02-17 12:57 UTC, networkException commented on src/commands/githubCommand.ts
> +} from "../util/embedFromIssueOrPull";
Please run prettier here

2022-02-17 12:58 UTC, networkException commented
> I have absolutely no idea how to squash the merge commit

Its best to drop that commit and rebase your branch on top of `master`, see [this video](https://youtu.be/ElRzTuYln0M) for guidance

2022-02-19 18:24 UTC, u9g commented on src/commands/githubCommand.ts
> +} from "../util/embedFromIssueOrPull";
done

2022-02-19 20:03 UTC, u9g commented on src/commandHandler.ts
> +            console.trace("matchedCommand.handle(Select|Context)Menu failed", error);
done

2022-02-19 20:03 UTC, u9g commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
done

2022-02-19 20:05 UTC, u9g commented on src/commandHandler.ts
> +                    name.toLowerCase() === interaction?.message?.interaction?.commandName
done

2022-02-19 20:45 UTC, networkException requested changes

2022-02-19 20:45 UTC, networkException commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
You don't need to run seperate searches with `is: pr` and `is: issue`, the api returns both if not specified otherwise

2022-02-19 21:12 UTC, u9g commented on src/util/embedFromIssueOrPull.ts
> + */
fixed

2022-02-19 21:12 UTC, u9g commented on src/commandHandler.ts
> +                content: "I don't recognize that command. Try **!help**.",
fixed

2022-02-19 21:12 UTC, u9g commented on src/commands/githubCommand.ts
> -    }
done

2022-02-19 22:00 UTC, bgianfo commented on src/apis/githubAPI.ts
> +            repo: "SerenityOS/serenity",
We can reuse the existing `repository` variable here.

2022-02-19 22:02 UTC, bgianfo commented on src/commands/userCommand.ts
> +        const clsoedIssueEmoji = (await getClosedIssue(interaction.client))?.toString() ?? "";
Typo in the variable name.

2022-02-19 22:32 UTC, u9g commented on src/commands/userCommand.ts
> +        const clsoedIssueEmoji = (await getClosedIssue(interaction.client))?.toString() ?? "";
fixed

2022-02-19 22:32 UTC, u9g commented on src/apis/githubAPI.ts
> +            repo: "SerenityOS/serenity",
done

2022-02-19 22:36 UTC, networkException commented
Have you seen my new comment on `fetchUserIssuesAndPulls`?

2022-02-19 22:52 UTC, u9g commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
I think you read [this](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-only-issues-or-pull-requests) and believe that.

However, in the intellisense from the .d.ts file, there is this comment: `To get results for both issues and pull requests, you must send separate queries for issues and pull requests.`

It links to that too, but when I tried without specifying, I only got issue responses.

2022-02-19 22:53 UTC, u9g commented
> Have you seen my new comment on `fetchUserIssuesAndPulls`?

Replied :)

2022-02-19 22:56 UTC, networkException commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
Hm ok, is it possible to make a request by hand using an url (aka just having octokit provide an access token)? The rest api seems to respond with both issues and pull requests just fine.

2022-02-19 23:14 UTC, u9g commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
Is there a reason to if this works fine?

2022-02-19 23:14 UTC, networkException commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
Well it uses our api quota

2022-02-19 23:21 UTC, u9g commented on src/apis/githubAPI.ts
> +    async fetchUserIssuesAndPulls(username: string): Promise<UserIssuesAndPulls> {
Yes, but 2 requests vs one request will make no difference except another however long of working on this, compared to it not actually being a problem at the moment. In the current bot's usage, this is not a needed optimization.

2022-02-24 01:31 UTC, bgianfo commented
@u9g Are you going to take care of the conflict?

2022-02-24 01:35 UTC, u9g commented
> @u9g Are you going to take care of the conflict?

resolved :)

2022-02-24 01:38 UTC, bgianfo commented
Your commit message doesn't make sense, given the change?

2022-02-24 02:16 UTC, u9g commented
> Your commit message doesn't make sense, given the change?

okay 😅 fixed it this time without wiping out all commits

2022-02-26 03:33 UTC, merged