Commands: Add a brand spanking new `commit-stats` command
SerenityOS/discord-bot pull request #707
Opened 2022-11-03 14:01 UTC by filiphsps

![image](https://user-images.githubusercontent.com/108444335/199740746-09fc1733-4f70-43dd-a975-2ca99e6672ec.png)

Oh wow, can be yours for a s little as $0, yes even in Nebraska!  Now ain't that a damn good deal!!

2022-11-03 15:04 UTC, filiphsps commented
@networkException - tagging per request

2022-11-04 22:09 UTC, networkException requested changes
This is a really neat command!

Sadly it doesn't seem to be very reliable with counting commits.. (at least I'm pretty sure that I have commits in `serenity` :^) )

![image](https://user-images.githubusercontent.com/42888162/200082056-60e7dd6e-4db2-404b-9e7d-ac732952c2b0.png)

Maybe (ab)using GitHub's pagination api with 1 item per page + getting the number of pages (see https://docs.github.com/en/rest/overview/resources-in-the-rest-api#link-header and perhaps https://www.npmjs.com/package/parse-link-header) would be more robust.

2022-11-06 11:41 UTC, filiphsps commented
> This is a really neat command!
> 
> Sadly it doesn't seem to be very reliable with counting commits.. (at least I'm pretty sure that I have commits in `serenity` :^) )
> 
> ![image](https://user-images.githubusercontent.com/42888162/200082056-60e7dd6e-4db2-404b-9e7d-ac732952c2b0.png)
> 
> Maybe (ab)using GitHub's pagination api with 1 item per page + getting the number of pages (see [docs.github.com/en/rest/overview/resources-in-the-rest-api#link-header](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#link-header) and perhaps [npmjs.com/package/parse-link-header](https://www.npmjs.com/package/parse-link-header)) would be more robust.

Alright, this has finally been resolved. I've also made the command a lot more reliable by allowing `getCommitsCount` multiple attempts while also respecting the github ratelimiting timeout.

I had initially planned to add a quick and dirty in-memory cache but decided that against it since it's highly unlikely somebody will run the command with the same parameters in a short time span. The `fetchSerenityRepos` function could be cached in the future, however.

(The rate limiting is solvable by instead using github's webhooks and our own database, might be interesting in the future but way out of scope for this PR). 🤠

2022-11-06 17:21 UTC, networkException approved these changes
One minor nit, LGTM otherwise

2022-11-06 17:21 UTC, networkException commented on src/apis/githubAPI.ts
> +                });
can we do something like

```suggestion
                await new Promise(resolve => setTimeout(resolve, timeout));
                
                // try { ...
```

instead?

2022-11-06 19:20 UTC, filiphsps commented on src/apis/githubAPI.ts
> +                });
Done 🤠

2022-11-06 20:42 UTC, networkException approved these changes

2022-11-06 20:47 UTC, merged