Deps+Everywhere: Upgrade `discord.js` to `v14`
SerenityOS/discord-bot pull request #720
Opened 2022-11-09 09:31 UTC by filiphsps

Additionally, every command now
  - uses the `SlashCommandBuilder` instead of directly providing JSON.
  - have their handlers properly typed.

Some parts of this commit are based on @bgianfo's work in #647.

2022-11-09 21:57 UTC, bgianfo commented
You have no idea how happy I am to see this PR, thank you! :blue_heart: :green_heart: :purple_heart: :yellow_heart:

2022-11-25 22:23 UTC, bgianfo requested changes
Just some questions and small nit picks.

2022-11-25 22:23 UTC, bgianfo commented on src/commandHandler.ts
> +                4
Can we use named arguments for this to make it clear this is for the number of spaces to use as indention?

2022-11-25 22:23 UTC, bgianfo commented on src/commands/userCommand.ts
> +        if (rows.length === 0) throw new Error("");
Real error message?

2022-11-25 22:25 UTC, bgianfo commented on src/util/embedFromIssueOrPull.ts
> +                value: `<t:${new Date(pull.created_at).valueOf() / 1000}:R>`,
Is there a better way to do this that discord provides? We don't need to do it in this PR, but it seems like we should probably factor this out into a utility if `discord.js` doesn't provide one?

2022-11-26 12:53 UTC, filiphsps commented on src/commandHandler.ts
> +            Object.values(Commands).map(commandClass => {
It iterates over everything that’s (named and) “exported” from the commands file without any safe guards, hypothetically you could export the Command base class in the same way and break it, but that doesn’t fit our current structure would be catched with a test.

2022-11-26 12:55 UTC, filiphsps commented on src/util/embedFromIssueOrPull.ts
> +                value: `<t:${new Date(pull.created_at).valueOf() / 1000}:R>`,
This isn’t something that was done as a part of this upgrade, it existed beforehand. With that said; yes there might be a way to do this “properly”, I’ll take a look as a while fixing the error messages :)

2022-11-26 12:56 UTC, filiphsps commented on src/commandHandler.ts
> +                4
You’re right, I completely forgot the best thing to ever happen to typescript; named parameters.

2022-11-26 12:57 UTC, filiphsps commented on src/commandHandler.ts
> +                4
Is that a thing in typescript now? If that’s the case then have completely missed that, awesome!

2022-11-30 05:23 UTC, filiphsps commented on src/util/embedFromIssueOrPull.ts
> +                value: `<t:${new Date(pull.created_at).valueOf() / 1000}:R>`,
Turns out that yes; there is a utility function for it!

2022-11-30 05:26 UTC, filiphsps commented on src/commandHandler.ts
> +                4
> Can we use named arguments for this to make it clear this is for the number of spaces to use as indention?

I looked into "named arguments/parameters" isn't really a thing in js/ts, the usual way to handle this is to take an object as input instead; however, this is a built-in function that doesn't support that.

2022-11-30 05:28 UTC, filiphsps commented on src/commandHandler.ts
> +            Object.values(Commands).map(commandClass => {
> How does this avoid the abstract `Command` base class that everything derives from? I honestly don't know that much javascript/typescript, so mostly asking out of curiosity.

Basically, what we get from `Commands` is the following:
```javascript
{
  CommitStatsCommand: [Getter],
  EmojiCommand: [Getter],
  GithubCommand: [Getter],
  ManCommand: [Getter],
  PlanCommand: [Getter],
  QuickLinksCommand: [Getter],
  QuoteCommand: [Getter],
  Test262Command: [Getter],
  UserCommand: [Getter]
}
```

Unless we start exporting `Command` as a non-default it won't be a part of the `Object.values(Commands)` array/list.

2022-11-30 06:27 UTC, bgianfo commented on src/commandHandler.ts
> +                4
Sure, I guess I was thinking about explicit object member names. Sorry about that.

2022-11-30 06:28 UTC, bgianfo commented on src/util/embedFromIssueOrPull.ts
> +                value: `<t:${new Date(pull.created_at).valueOf() / 1000}:R>`,
cool! thanks

2022-11-30 06:29 UTC, bgianfo approved these changes

2022-11-30 06:30 UTC, merged