Commands: Add emoji command
SerenityOS/discord-bot pull request #85
Opened 2021-06-20 20:41 UTC by networkException

This command allows non nitro users to send animated emojis (or any emoji)
from the configured guild into the current chat

2021-06-20 20:50 UTC, bgianfo commented
This should either use the common embed framework so that it shows what user issued the command, or it needs to be a part of this commands output. The ability to anonymously issue memorable commands is asking for assholes and abusers to take advantage without any way for the mods to take action (no accountability).

2021-06-20 20:55 UTC, bgianfo requested changes
Needs user in the command output.

2021-06-20 21:00 UTC, networkException commented
What do you think of this?

![image](https://user-images.githubusercontent.com/42888162/122688213-3c25eb00-d21b-11eb-911c-8f5c3f04435a.png)

2021-06-21 18:16 UTC, bgianfo commented
Sure, that works.

2021-06-21 18:16 UTC, merged

2021-06-21 18:21 UTC, networkException commented
Yo yo I didn't commit those changes yet :smile: